### ISSUE TITLE
Make Germplasm List in AGILE Project Downloadable.

### ISSUE THREAD

**Issue by reynoldtan** [UofS-Pulse-Binfo/kp_nodes#4]
Add a download link to download germplasm list in csv format.

**Comment by Jiu9Shen** [comment]
The download file name is "agile-_application_of_genomic_innovation_in_the_lentil_economy_germplasm_list.csv", which is quite long. Can you give another name because agile is short for "application_of_genomic_innovation_in_the_lentil_economy" and kind of repeat to include both in the file name.

**Comment by laceysanderson** [comment]
Fixed in above pull request
