### ISSUE TITLE
Support short version of AGILE page url.

### ISSUE THREAD

**Issue by reynoldtan** [UofS-Pulse-Binfo/kp_nodes#9]
Support use of short page url ie. KnowPulse/AGILE to redirect to project page.

**Comment by laceysanderson** [comment]
I don't think this needs any custom code. Instead we can use `URL redirects` which works for both nodes and the new Tripal entities and can be set through the UI.

How to redirect a page using URL redirect:
1. Go to the node/entity page you want to redirect to (e.g. http://knowpulse.usask.ca/portal/project/AGILE%3A-Application-of-Genomic-Innovation-in-the-Lentil-Economy)
2. Click Edit and scroll to the bottom of the form.
3. Click "URL Redirects" then "Add URL redirect to this [node]"
4. Set the details for the Redirect and save.
![screen shot 2018-10-29 at 9 06 07 pm](https://user-images.githubusercontent.com/1566301/47693264-a1d28e00-dbbe-11e8-9021-5c64712d213d.png)

**Comment by laceysanderson** [comment]
Solved on production site
